### ISSUE TITLE
Feature Request: specify temporary directory (for ffmpeg processing)

### ISSUE THREAD

**Issue by apocalyptech** [inbasic/iaextractor#100]
When doing automatic ffmpeg processing, iaextractor currently uses a call to FileUtils.getDir("TmpD", foo) to create a temporary directory.  This happens here:

https://github.com/inbasic/iaextractor/blob/master/src/lib/ffmpeg.js#L82

My system's temp directory is on a separate partition, and for some larger 1080p videos, this can end up running out of space.  It'd be great to be able to specify an alternate directory to use inside the preferences, rather than just TmpD.

It looks like "TmpD" is referenced in at least one other file as well, so possibly that'd need to be updated in more than just ffmpeg.js.

Thanks for the utility, btw!  It works great, and has been super useful.

**Comment by inbasic** [comment]
Thanks for the report. In the latest dev version, https://github.com/inbasic/iaextractor/blob/beta/src/iaextractor.xpi?raw=true if user creates a preference with the following detail:
name: extensions.feca4b87-3be4-43da-a1b1-137c24220968@jetpack.tmp-dir
value: path to the temporary folder

this folder will be used instead of the system's default temporary folder.
