### ISSUE TITLE
[published_date] not showing up in name of downloaded file

### ISSUE THREAD

**Issue by piman31416** [inbasic/iaextractor#109]
Hi! Love the plugin. One thing isn't working for me: I have file-naming pattern set to include [published_date] as part of the file name. However, it works only some of the time, whereas other parameters such as [video_resolution] always work. I can't establish why this is, though it seems to be more reliable if the date is 2013 or later. Using German version of Firefox 42.0 on German Windows 8.1. YouTube is set to US English.

**Comment by zjohn4** [comment]
Been a year since this was opened, which isnt great.. But I too have this issue. I think its only worked once ever for me, which was after newly installing and so i think perhaps it has to do with my setup for the filenames.

Im not expecting language to affect this but since OP mentioned it, mine is all English (UK or US, whatevers available).
Filename pattern: "[author] - [file_name] ([video_id];[published_date]).[extension]"

They all have their uses and the date is the only one that hasnt worked, very helpful for sorting, based first on uploader then by date. I might have mentioned elsewhere to dev about modifying the style of date as well (such as using ISO-8601, or plain text) but thats irrelevant if this tag doesnt work at all.

**Comment by inbasic** [comment]
So is there any re-produceable steps for this?

**Comment by inbasic** [comment]
I have tried the `[published_date]` on a few pages and it works as expected. Please reopen with an instruction on how to generate the bug if you are still experiencing the issue.
