### ISSUE TITLE
it is not bug only request...

### ISSUE THREAD

**Issue by JesWhite** [inbasic/iaextractor#133]
hi...
i want to a question..
i like your addon.
and i saw only a problem.
there isn't any way to download audio from opus to convering mp3?
i want to down mp3...
but it is need to 2. extra working..thanks.

**Comment by inbasic** [comment]
Well, the reason the option is not there is because it is not recommended.
Anyhow if you are sure you will need MP3, open options page and go to the FFmpeg integration tab. Now overwrite audio extraction command by MP3 conversion command.

Note that you can play with FFmpeg to get both files as well.
